OPC-41 - Configurando a conexão com o banco de dados.
free-open-connect/core-service pull request #1
Opened 2022-12-16 20:17 UTC by Renato-Queiroz

OPC-41 - Configurando a conexão com Postgres.

2022-12-16 20:25 UTC, CharlesQueiroz requested changes
Por favor, realizar os ajustes apontados.

2022-12-16 20:25 UTC, CharlesQueiroz commented on src/main/resources/application.properties
> +# Database Properties
Por favor, converter o arquivo application.properties no formato .yml.

2022-12-16 20:25 UTC, CharlesQueiroz commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
Para todas as propriedades, usar variáveis de ambiente no formato: 

`spring.datasource.username=${DATASOURCE_USERNAME:postgres}`

...

2022-12-16 20:25 UTC, CharlesQueiroz commented on src/main/resources/application.properties
> +# Hibernate ddl auto (create, create-drop, validate, update)
remover este comentário.

2022-12-16 20:28 UTC, CharlesQueiroz requested changes
Por favor, implementar conforme solicitado.

2022-12-16 21:07 UTC, Renato-Queiroz commented on src/main/resources/application.properties
> +# Hibernate ddl auto (create, create-drop, validate, update)
corrigido.

2022-12-16 21:56 UTC, Renato-Queiroz commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
realizado ajuste.

2022-12-16 21:56 UTC, Renato-Queiroz commented on src/main/resources/application.properties
> +# Database Properties
realizado alteração.

2022-12-17 00:35 UTC, CharlesQueiroz requested changes
Realizar os ajustes

2022-12-17 00:35 UTC, CharlesQueiroz commented on src/main/resources/application.yml
> +    open-in-view: 'false'
Criar uma variável aqui tb

2022-12-17 00:35 UTC, CharlesQueiroz commented on src/main/resources/application.yml
> +      ddl-auto: update
Criar uma variável aqui tb

2022-12-17 00:35 UTC, CharlesQueiroz commented on src/main/resources/application.yml
> +    url: jdbc:postgresql://localhost:5432/postgres
Criar uma variável aqui tb

2022-12-17 00:35 UTC, CharlesQueiroz commented on pom.xml
> +            <version>42.5.1</version>
Criar uma variável aqui tb

2022-12-17 15:10 UTC, Renato-Queiroz commented on pom.xml
> +            <version>42.5.1</version>
corrigido.

2022-12-17 15:10 UTC, Renato-Queiroz commented on src/main/resources/application.yml
> +    url: jdbc:postgresql://localhost:5432/postgres
corrigido.

2022-12-17 15:10 UTC, Renato-Queiroz commented on src/main/resources/application.yml
> +      ddl-auto: update
corrigido.

2022-12-17 15:11 UTC, Renato-Queiroz commented on src/main/resources/application.yml
> +    open-in-view: 'false'
corrigido.

2022-12-17 15:25 UTC, CharlesQueiroz approved these changes

2022-12-17 18:21 UTC, PaulocastroDEV approved these changes

2022-12-18 13:22 UTC, CharlesQueiroz approved these changes

2022-12-18 13:23 UTC, merged