OPC-46 Configurar o p6spy no projeto core-service
free-open-connect/core-service pull request #3
Opened 2022-12-17 17:22 UTC by Renato-Queiroz

Favor analisar.

2022-12-17 18:17 UTC, CharlesQueiroz requested changes

2022-12-17 18:17 UTC, CharlesQueiroz commented on pom.xml
> +            <version>1.8.1</version>
Extrair para uma variável aqui.

2022-12-17 21:52 UTC, Renato-Queiroz commented on pom.xml
> +            <version>1.8.1</version>
corrigido.

2022-12-18 13:01 UTC, CharlesQueiroz approved these changes

2022-12-18 16:16 UTC, CharlesQueiroz approved these changes

2022-12-18 16:54 UTC, Thiagodd approved these changes
👍🏻

2022-12-18 16:54 UTC, merged